node {
	def buildFile     = './code/build.gradle'
	def buildWrapper  = './code/gradlew'
	def branchName    = "${env.BRANCH_NAME}"
	setupEnvironment()
	//printParams()
	
		stage ('checkout'){ 
			echo "test"
			checkout scm
		}
		stage ('build'){
			echo "Building on branch: ${branchName}"
			echo "Building : ${env.JOB_NAME}"
		    if(isUnix()) {
				//println Running on Linux slave
				sh "${buildWrapper} -b ${buildFile} buildrun"
			}
			else{
				//println Running on Windows slave
				bat "${buildWrapper} -b ${buildFile} buildrun"
			}
		}

		stage ('test'){
			 echo "Running tests on branch: ${branchName}"

				if(isUnix()) {
					//println Running on Linux slave
					sh "${buildWrapper} -b ${buildFile} testrun"
				}
				else{
					//println Running on Windows slave
					bat "${buildWrapper} -b ${buildFile} testrun"
				}
				//step([$class: 'JUnitResultArchiver', testResults: 'TEST-*.xml'])


		}
	}
	def setupEnvironment() {
		//def javaHome = tool(name: 'Oracle JDK8 Autoinstall')
		def jobName = "${env.JOB_NAME}"
		print "---"+jobName 
		script {
            //env.jdk_home = "${javaHome}"
			if(jobName){
				env.isCIEnabled= "true"
			}else{
				env.isCIEnabled= "false"
			}
        }
	}


def printParams() {
    println "test"
}

