node {
	def buildFile     = './code/build.gradle'
	def buildWrapper  = './code/gradlew'
	def javaHome = tool(name: 'Oracle JDK8 Autoinstall')
	
	def customEnv = setupEnvironment()
	withEnv(customEnv) {
		stage ('checkout'){ 
			echo "test"
			checkout scm
		}
		stage ('build'){
			echo "Building on branch: ${env.BRANCH_NAME}"
			echo "${javaHome}"
			script {
                    env.JAVA_HOME = "${javaHome}"
                }
            echo "${env.JAVA_HOME}"
			if(isUnix()) {
				//println Running on Linux slave
				sh "${buildWrapper} -b ${buildFile} buildrun"
			}
			else{
				//println Running on Windows slave
				bat "${buildWrapper} -b ${buildFile} buildrun"
			}
		}

		stage ('test'){
			 echo "Running tests on branch: ${env.BRANCH_NAME}"

				if(isUnix()) {
					//println Running on Linux slave
					sh "${buildWrapper} -b ${buildFile} testrun"
				}
				else{
					//println Running on Windows slave
					bat "${buildWrapper} -b ${buildFile} testrun"
				}
				//step([$class: 'JUnitResultArchiver', testResults: '*/TEST-*.xml'])


		}
	}
}
	def setupEnvironment() {
	  def javaHome = tool(name: 'OpenJDK 8')
	  def customEnv = ["PATH+JAVA_HOME=${javaHome}"]
	  return customEnv
	}

